### ISSUE TITLE
Tag Heading gets smaller and smaller when more than a few tags are added

### ISSUE THREAD

**Issue by ideal4ever** [aistra0528/Hail#13]
hi, i know it's not a big issue, but i thought it's a piece of cake for the developers to fix. as i add more tags, the bar where tag headings are shown, gets more and more compacted and the tag titles become smaller and smaller and unrecognisable. 
i let you guys decide how to remedy this, but i want you to know i do appreciate it a lot.
here's an screenshot : https://imgur.com/a/ZvMZOXU

**Comment by Pr0pHesyer** [comment]
https://developer.android.com/guide/navigation/navigation-swipe-view#add_tabs_using_a_tablayout

This is a way to try in fragment_home.xml
