### ISSUE TITLE
Add  Screen Off Freeze Delay

### ISSUE THREAD

**Issue by Pr0pHesyer** [aistra0528/Hail#14]
In most time,we don't need to freeze Apps when screen off.Add a clock, then freeze Apps when the clock ring.
Maybe I can't do it by myself, I appreciate each developer of this program.
Thx

**Comment by Pr0pHesyer** [comment]
https://github.com/Pr0pHesyer/Hail/commit/e0d792dbf99fa61ce23d0504632468ad6ab72402

Add a delay switch for delaying 60 seconds. This is based on 'SwitchPreferenceCompat', but I believe there is aother developer who can develop it for custom time.

**Comment by aistra0528** [comment]
added #44
