### ISSUE TITLE
如何取消设备管理者权限？

### ISSUE THREAD

**Issue by zhengweiqing** [aistra0528/Hail#141]
我用命令 adb shell dpm set-device-owner com.aistra.hail/.receiver.DeviceAdminReceiver
将Hail设置为了设备管理者，但我是安装在车机上，车机没有 “设置 > 移除设备所有者“ 这一项，请问我要如何移除设备所有者呢？

**Comment by andy-math** [comment]
需要使用`adb shell dpm remove-active-admin com.aistra.hail/.receiver.DeviceAdminReceiver`
如果hail app拒绝这个请求（出于安全考虑，很有可能会拒绝强制移除），那么很可能需要重置整个车机

**Comment by aistra0528** [comment]
如果在雹设置界面工具栏上没有移除设备所有者的选项，也可以在应用界面中找到雹本身，长按后在弹出的对话框中选择卸载。
如果雹是设备所有者的话，这样做应该会弹出移除设备所有者的对话框。
