### ISSUE TITLE
Permission denied when using Shizuku-Hide Method

### ISSUE THREAD

**Issue by 0-BlackSpectrum-0** [aistra0528/Hail#170]
As the title says permission is denied when I try to use shizuku hide method, shizuku disable works fine.
More details in screenshots attached.
![SmartSelect_20231125-202124_Hail.jpg](https://github.com/aistra0528/Hail/assets/79910450/b18e12c4-b8d0-4ac0-ae8d-21e20a77c407)

![SmartSelect_20231125-202041_Shizuku.jpg](https://github.com/aistra0528/Hail/assets/79910450/3b70c83a-dd65-4abc-9c99-d7f49635ff76)

![Screenshot_20231125-202150_Hail.png](https://github.com/aistra0528/Hail/assets/79910450/7b569b67-78e7-4bd9-889a-310c7dd90118)

![SmartSelect_20231125-202056_Shizuku.jpg](https://github.com/aistra0528/Hail/assets/79910450/cd718447-1e5a-4405-8154-bb079826bd0f)

**Comment by fallsdevil** [comment]
Yes, I'm having the same problem on one of my devices with Android 10 just...

**Comment by SychoAN** [comment]
> As the title says permission is denied when I try to use shizuku hide method, shizuku disable works fine. More details in screenshots attached. ![SmartSelect_20231125-202124_Hail.jpg](https://private-user-images.githubusercontent.com/79910450/285598768-b18e12c4-b8d0-4ac0-ae8d-21e20a77c407.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg3OTAsIm5iZiI6MTcwMzA2ODQ5MCwicGF0aCI6Ii83OTkxMDQ1MC8yODU1OTg3NjgtYjE4ZTEyYzQtYjhkMC00YWMwLWFlOGQtMjFlMjBhNzdjNDA3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NDM1NDgwNzAyMDEyNzBkMWIyZjI2NWI4ZWIxMzYyOWU3NWVjOWQ5YzcwMTU1MTJjNWVhMmY3YjNhNDdhYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GmFC7cltanPTaLXm6U69yWkx-ijbgVSe1wXPPpfI7Pc)
> 
> ![SmartSelect_20231125-202041_Shizuku.jpg](https://private-user-images.githubusercontent.com/79910450/285598767-3b70c83a-dd65-4abc-9c99-d7f49635ff76.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg3OTAsIm5iZiI6MTcwMzA2ODQ5MCwicGF0aCI6Ii83OTkxMDQ1MC8yODU1OTg3NjctM2I3MGM4M2EtZGQ2NS00YWJjLTljOTktZDdmNDk2MzVmZjc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZTc4NWJlYWY1MTE1Yzc1MGJkNDZmNzM1MjU0NDczNTU5OTQ5MzBkZjA1MzU1YTgwZWE4YTVkMmYzNmY4MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eRycSI1E6o_RuWHOG5ngyBSYsbAbNyamABga0H4-o4U)
> 
> ![Screenshot_20231125-202150_Hail.png](https://private-user-images.githubusercontent.com/79910450/285598766-7b569b67-78e7-4bd9-889a-310c7dd90118.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg3OTAsIm5iZiI6MTcwMzA2ODQ5MCwicGF0aCI6Ii83OTkxMDQ1MC8yODU1OTg3NjYtN2I1NjliNjctNzhlNy00YmQ5LTg4OWEtMzEwYzdkZDkwMTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZTZlODA1NjZmMTZmYzdhYTkxZTAyYzk1ZjM4NzhkNmE4MzQ2ZDY4MmI5MzExNzVlNGVhMGYyODJlNjJjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TqjReqdF8d4B7GBd4UYut7F51sElOzk9k9bsy0wiK94)
> 
> ![SmartSelect_20231125-202056_Shizuku.jpg](https://private-user-images.githubusercontent.com/79910450/285598765-cd718447-1e5a-4405-8154-bb079826bd0f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg3OTAsIm5iZiI6MTcwMzA2ODQ5MCwicGF0aCI6Ii83OTkxMDQ1MC8yODU1OTg3NjUtY2Q3MTg0NDctMWU1YS00NDA1LTgxNTQtYmIwNzk4MjZiZDBmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZTM1MWJmOTY2MGExODQyMWYxMjYwMjA4ZTQ2OWNmYjY0YmRiMDkwMjFlZjZmYWMxM2E2MzZhNjIxZThhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRw8_C58RRM6EjmEPbMaXZxfb3yWmkKgBm-n_nLnQfY)

Can I ask what is your font name 🙂 ?
it looks amazing

**Comment by Black-StellarSpectrum** [comment]
> > As the title says permission is denied when I try to use shizuku hide method, shizuku disable works fine. More details in screenshots attached. ![SmartSelect_20231125-202124_Hail.jpg](https://private-user-images.githubusercontent.com/79910450/285598768-b18e12c4-b8d0-4ac0-ae8d-21e20a77c407.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg3OTAsIm5iZiI6MTcwMzA2ODQ5MCwicGF0aCI6Ii83OTkxMDQ1MC8yODU1OTg3NjgtYjE4ZTEyYzQtYjhkMC00YWMwLWFlOGQtMjFlMjBhNzdjNDA3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NDM1NDgwNzAyMDEyNzBkMWIyZjI2NWI4ZWIxMzYyOWU3NWVjOWQ5YzcwMTU1MTJjNWVhMmY3YjNhNDdhYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GmFC7cltanPTaLXm6U69yWkx-ijbgVSe1wXPPpfI7Pc)
> > 
> > ![SmartSelect_20231125-202041_Shizuku.jpg](https://private-user-images.githubusercontent.com/79910450/285598767-3b70c83a-dd65-4abc-9c99-d7f49635ff76.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg3OTAsIm5iZiI6MTcwMzA2ODQ5MCwicGF0aCI6Ii83OTkxMDQ1MC8yODU1OTg3NjctM2I3MGM4M2EtZGQ2NS00YWJjLTljOTktZDdmNDk2MzVmZjc2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZTc4NWJlYWY1MTE1Yzc1MGJkNDZmNzM1MjU0NDczNTU5OTQ5MzBkZjA1MzU1YTgwZWE4YTVkMmYzNmY4MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eRycSI1E6o_RuWHOG5ngyBSYsbAbNyamABga0H4-o4U)
> > 
> > ![Screenshot_20231125-202150_Hail.png](https://private-user-images.githubusercontent.com/79910450/285598766-7b569b67-78e7-4bd9-889a-310c7dd90118.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg3OTAsIm5iZiI6MTcwMzA2ODQ5MCwicGF0aCI6Ii83OTkxMDQ1MC8yODU1OTg3NjYtN2I1NjliNjctNzhlNy00YmQ5LTg4OWEtMzEwYzdkZDkwMTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZTZlODA1NjZmMTZmYzdhYTkxZTAyYzk1ZjM4NzhkNmE4MzQ2ZDY4MmI5MzExNzVlNGVhMGYyODJlNjJjYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TqjReqdF8d4B7GBd4UYut7F51sElOzk9k9bsy0wiK94)
> > 
> > ![SmartSelect_20231125-202056_Shizuku.jpg](https://private-user-images.githubusercontent.com/79910450/285598765-cd718447-1e5a-4405-8154-bb079826bd0f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjg3OTAsIm5iZiI6MTcwMzA2ODQ5MCwicGF0aCI6Ii83OTkxMDQ1MC8yODU1OTg3NjUtY2Q3MTg0NDctMWU1YS00NDA1LTgxNTQtYmIwNzk4MjZiZDBmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEwMzQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZTM1MWJmOTY2MGExODQyMWYxMjYwMjA4ZTQ2OWNmYjY0YmRiMDkwMjFlZjZmYWMxM2E2MzZhNjIxZThhODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRw8_C58RRM6EjmEPbMaXZxfb3yWmkKgBm-n_nLnQfY)
> 
> Can I ask what is your font name 🙂 ?
> it looks amazing

It's **Atomic Age**

**Comment by jasonkhoo87** [comment]
I am having the same problem too with Shizuku - Hide and Shizuku - Suspend mode.

Device: Oppo A31
System: ColorOS v6.1.2 (Android 9)

**Comment by Jesse205** [comment]
https://github.com/aistra0528/Hail/pull/176

This pr is supposed to fix this issue.

**Comment by Jesse205** [comment]
> #176
> 
> This pr is supposed to fix this issue.
I'm very sorry, I misread this pr, this pr is not a fix for this issue

**Comment by aistra0528** [comment]
Adb can't hide apps, you should run Shizuku with root. i will add tips in the next release.

**Comment by Black-StellarSpectrum** [comment]
> Adb can't hide apps, you should run Shizuku with root. i will add tips in the next release.

But I think it can, you can hide apps using "pm uninstall" command on adv when connected to pc, what you can't do is uninstall system apps that requires root!
I've hidden many apps using this command and recently I found a pc tool that does this thing I forgot the name, but the thing is it requires a pc, and some apps everytime returns back, so it'd be more convenient if I can do that on my phone.
So is the feature I'm talking about called hide in hail, or something else? I want to use that.

**Comment by Jesse205** [comment]
> > Adb can't hide apps, you should run Shizuku with root. i will add tips in the next release.
> 
> But I think it can, you can hide apps using "pm uninstall" command on adv when connected to pc, what you can't do is uninstall system apps that requires root!
> I've hidden many apps using this command and recently I found a pc tool that does this thing I forgot the name, but the thing is it requires a pc, and some apps everytime returns back, so it'd be more convenient if I can do that on my phone.
> So is the feature I'm talking about called hide in hail, or something else? I want to use that.

I think this is considered uninstalling software, not freezing software.

**Comment by aistra0528** [comment]
> > Adb can't hide apps, you should run Shizuku with root. i will add tips in the next release.
> 
> But I think it can, you can hide apps using "pm uninstall" command on adv when connected to pc, what you can't do is uninstall system apps that requires root! I've hidden many apps using this command and recently I found a pc tool that does this thing I forgot the name, but the thing is it requires a pc, and some apps everytime returns back, so it'd be more convenient if I can do that on my phone. So is the feature I'm talking about called hide in hail, or something else? I want to use that.

![IMG_20240111_015625](https://github.com/aistra0528/Hail/assets/55940744/3302482c-9ba6-495c-bae5-db81424a08d1)
Uninstall = `pm uninstall`
Hide = `pm hide`

**Comment by Black-StellarSpectrum** [comment]
> > > Adb can't hide apps, you should run Shizuku with root. i will add tips in the next release.
> > 
> > But I think it can, you can hide apps using "pm uninstall" command on adv when connected to pc, what you can't do is uninstall system apps that requires root! I've hidden many apps using this command and recently I found a pc tool that does this thing I forgot the name, but the thing is it requires a pc, and some apps everytime returns back, so it'd be more convenient if I can do that on my phone. So is the feature I'm talking about called hide in hail, or something else? I want to use that.
> 
> ![IMG_20240111_015625](https://github.com/aistra0528/Hail/assets/55940744/3302482c-9ba6-495c-bae5-db81424a08d1)
> Uninstall = `pm uninstall`
> Hide = `pm hide`

Thanks, I tried uninstall, but Hail crashed, tried multiple times, uninstalling sys app, but Hail is crashing! I don't have root but it should work proof (https://xdaforums.com/t/uninstall-bloatwares-no-root.4321387/)

**Comment by Black-StellarSpectrum** [comment]
> Can you show me the output of this?
> ![Screenshot](https://github.com/aistra0528/Hail/assets/55940744/1fcc3a7d-788f-47be-a1f7-43658c6072c5)
> 

Yup here you go:
Operation Failed: 255
```

Exception occurred while executing 'uninstall':
java.lang.IllegalArgumentException: Bad user number: O
	at android.os.UserHandle.parseUserArg(UserHandle.java:469)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1992)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:237)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26934)
	at android.os.Binder.shellCommand(Binder.java:965)
	at android.os.Binder.onTransact(Binder.java:839)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5360)
	at android.os.Binder.execTransactInternal(Binder.java:1195)
	at android.os.Binder.execTransact(Binder.java:1159)

```

**Comment by aistra0528** [comment]
> Yup here you go: Operation Failed: 255
> 
> ```
> 
> Exception occurred while executing 'uninstall':
> java.lang.IllegalArgumentException: Bad user number: O
> 	at android.os.UserHandle.parseUserArg(UserHandle.java:469)
> 	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1992)
> 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:237)
> 	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
> 	at android.os.ShellCommand.exec(ShellCommand.java:44)
> 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26934)
> 	at android.os.Binder.shellCommand(Binder.java:965)
> 	at android.os.Binder.onTransact(Binder.java:839)
> 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
> 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5360)
> 	at android.os.Binder.execTransactInternal(Binder.java:1195)
> 	at android.os.Binder.execTransact(Binder.java:1159)
> ```

User 0, not O

**Comment by Black-StellarSpectrum** [comment]
> > Yup here you go: Operation Failed: 255
> > 
> > ```
> > 
> > Exception occurred while executing 'uninstall':
> > java.lang.IllegalArgumentException: Bad user number: O
> > 	at android.os.UserHandle.parseUserArg(UserHandle.java:469)
> > 	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1992)
> > 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:237)
> > 	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
> > 	at android.os.ShellCommand.exec(ShellCommand.java:44)
> > 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26934)
> > 	at android.os.Binder.shellCommand(Binder.java:965)
> > 	at android.os.Binder.onTransact(Binder.java:839)
> > 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
> > 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5360)
> > 	at android.os.Binder.execTransactInternal(Binder.java:1195)
> > 	at android.os.Binder.execTransact(Binder.java:1159)
> > ```
> 
> User 0, not O

Oh my bad, just copy pasted it, OCR made an error, here's the result ![Screenshot_20240113-224010_Hail.png](https://github.com/aistra0528/Hail/assets/79910450/0dec3cdf-ef3e-4577-aa30-f76173f34a1c)

![Screenshot_20240113-224049_Hail.png](https://github.com/aistra0528/Hail/assets/79910450/8cdd8d9f-69f6-4d67-b4f5-44092eb8adb6)


One more thing while I'm here, why does the app automatically clears itself from the recents, just went to recent to copy or check stuff in app info and it's gone from the recent menu, can you fix that also?

**Comment by Black-StellarSpectrum** [comment]
> > > Yup here you go: Operation Failed: 255
> > > 
> > > ```
> > > 
> > > Exception occurred while executing 'uninstall':
> > > java.lang.IllegalArgumentException: Bad user number: O
> > > 	at android.os.UserHandle.parseUserArg(UserHandle.java:469)
> > > 	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1992)
> > > 	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:237)
> > > 	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
> > > 	at android.os.ShellCommand.exec(ShellCommand.java:44)
> > > 	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26934)
> > > 	at android.os.Binder.shellCommand(Binder.java:965)
> > > 	at android.os.Binder.onTransact(Binder.java:839)
> > > 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5206)
> > > 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5360)
> > > 	at android.os.Binder.execTransactInternal(Binder.java:1195)
> > > 	at android.os.Binder.execTransact(Binder.java:1159)
> > > ```
> > 
> > User 0, not O
> 
> Oh my bad, just copy pasted it, OCR made an error, here's the result ![Screenshot_20240113-224010_Hail.png](https://github.com/aistra0528/Hail/assets/79910450/0dec3cdf-ef3e-4577-aa30-f76173f34a1c)
> 
> ![Screenshot_20240113-224049_Hail.png](https://github.com/aistra0528/Hail/assets/79910450/8cdd8d9f-69f6-4d67-b4f5-44092eb8adb6)
> 
> 
> One more thing while I'm here, why does the app automatically clears itself from the recents, just went to recent to copy or check stuff in app info and it's gone from the recent menu, can you fix that also? 

Tried Uninstall again and it's working now, also that clearing from the recent menu was due to Biometrics ON I turned it off and it's not doing that now, but can you make it so it won't clear itself from recents if biometrics is on?
Thanks
