### ISSUE TITLE
能不能支持一下多开应用

### ISSUE THREAD

**Issue by AdamTyn** [aistra0528/Hail#180]
能不能支持一下多开应用

**Comment by andy-math** [comment]
使用 [island](https://github.com/oasisfeng/island) 工作模式可以多开

**Comment by scruel** [comment]
他值得应该是 MIUI 之类的多来应用，冰箱倒是支持显示和操作的

**Comment by scruel** [comment]
他指得应该是 MIUI 之类的多开应用，冰箱倒是支持显示和操作的

**Comment by scruel** [comment]
另外现在还有一个问题，MIUI 在多开应用的主应用被单独卸载后，仍然会显示在列表里，且不会像冰箱一样显示“（多开）”字样

**Comment by aistra0528** [comment]
#31
