### ISSUE TITLE
希望可以设置关机前解冻所有系统应用，避免无法开机的问题

### ISSUE THREAD

**Issue by ysy950803** [aistra0528/Hail#20]
部分ROM如MIUI，如果把不小心系统应用冻结了，重启后就无法开机了，MIUI直接Hard Code了各种应用包名，被冻结的话直接卡米，只能TWRP进`/data/system/users/0/`把`package-restrictions.xml`删了才行。
目前能想到的方法就是在关机前解冻，开机再冻结，不知道是否可行？

**Comment by aistra0528** [comment]
没有办法保证关机时一定能执行某些操作，特别是在设备意外卡死时。如有需求请考虑解除卡米限制（针对MIUI）或自动救砖模块。

**Comment by yenanrens** [comment]
用暂停模式对付系统应用，还会出现重启后就无法开机？
