### ISSUE TITLE
[Issue] Shizuku + suspend giving permission denied with new Android 14 update 

### ISSUE THREAD

**Issue by Aswin8** [aistra0528/Hail#202]
Using this app for an year in my Pixel 7. But getting permission denied error from yesterday. Any clue or resolution? or how to get logs... (using Shizuku + suspend mode for past 1 year) ( other Shizuku apps continue to work fine)

**Comment by MKBontwikkeling** [comment]
Same here. Also Pixel 7 (Pro). Issues with permission denied. Saw that it doesnt affect all apps though. The "Force Stop" option in the app settings of those apps also seem to be grayed out. Very weird.

**Comment by AyoungDukie** [comment]
Same here; I at least got around three force-stop issue by "Removing from home", but re-adding doesn't resolve the underlying problem

**Comment by aistra0528** [comment]
It seems like a Pixel issue. PR welcome.

**Comment by MKBontwikkeling** [comment]
> It seems like a Pixel issue. PR welcome.

I'm running GOS by the way

**Comment by Aswin8** [comment]
Looks like this is going to be wide spread with other devices getting the updates.

**Comment by AyoungDukie** [comment]
> It seems like a Pixel issue. PR welcome.

Another bit of info, I thought that my update was simplythe monthly security update, but was the March Android 14 QPR update. I did also see that Shizuku recently had an update specifically addressing this update, so perhaps there is something there (either in Hail's end or in Shizuku?)

**Comment by dogs-1985** [comment]
> It seems like a Pixel issue. PR welcome.

If I use "Shizuku - 停用" on system app, it show "没有权限".
If I use "Shizuku - 暂停" on system app, it show "已冻结".
If I use "Shizuku - 停用/暂停" on user app, without any problem.

Is anything I done wrong and not able to freeze the apps properly? I just installed the app yesterday.

Hail: 1.8.0 (31)
Shizuku: 13.5.4r1049.0e53409
OS: HyperOS (Android 14)

**Comment by aistra0528** [comment]
Try this:
https://github.com/aistra0528/Hail/actions/runs/8389628936/artifacts/1349790542
Is it working?

**Comment by Aswin8** [comment]
Works great now! Thank you

![Screenshot_20240322-172853](https://github.com/aistra0528/Hail/assets/11328626/ebeff38a-0b6e-492d-906b-5069d78dfd65)

![Screenshot_20240322-172844](https://github.com/aistra0528/Hail/assets/11328626/06870cc4-56c5-4e62-96dd-d63fbda55387)

**Comment by AyoungDukie** [comment]
Can also confirm this worked for my Pixel 8!

**Comment by dogs-1985** [comment]
> Try this: https://github.com/aistra0528/Hail/actions/runs/8389628936/artifacts/1349790542 Is it working?

Sorry, still not working. Even I use "Shizuku - 暂停" also prompt me "没有权限" in debug version. Normal version I still able to "暂停".

**Comment by aistra0528** [comment]
> Sorry, still not working. Even I use "Shizuku - 暂停" also prompt me "没有权限" in debug version. Normal version I still able to "暂停".

This fix is for AOSP.
HyperOS has a whitelist that prevents users from disabling("停用") system apps.
Can you tell me the date of your device's security patch update ("Android 安全补丁更新日期")?

**Comment by dogs-1985** [comment]
> > Sorry, still not working. Even I use "Shizuku - 暂停" also prompt me "没有权限" in debug version. Normal version I still able to "暂停".
> 
> This fix is for AOSP. HyperOS has a whitelist that prevents users from disabling("停用") system apps. Can you tell me the date of your device's security patch update ("Android 安全补丁更新日期")?

Is this "Android 安全更新"，wrote "2024-03-01"。

**Comment by dogs-1985** [comment]
> > Sorry, still not working. Even I use "Shizuku - 暂停" also prompt me "没有权限" in debug version. Normal version I still able to "暂停".
> 
> This fix is for AOSP. HyperOS has a whitelist that prevents users from disabling("停用") system apps. Can you tell me the date of your device's security patch update ("Android 安全补丁更新日期")?

https://xiaomi.eu/community/threads/in-hyperos-you-cant-disable-apps-via-adb.71469/

I found this post just now, I'm no idea what is adb and pm, but hope it will helps. If the hyperos cannot disable any system app, just let it be.
