### ISSUE TITLE
Feature request - add support for Tasker / MacroDroid for freezing specific categories

### ISSUE THREAD

**Issue by chaoscreater** [aistra0528/Hail#222]
Hi,

I have multiple categories for the different apps that I want to freeze. Instead of freezing all apps, I just want to freeze apps in a specific category, using either Tasker or MacroDroid. If Hail can expose the intent to freeze specific categories, then I'll be able to automate this using Tasker/Macrodroid.

**Comment by palmuse** [comment]
This exists. Look at the API section on readme.

Here is English translation:

API

adb shell am start -a action -e name value

action can be:

com.aistra.hail.action.LAUNCH: Unfreeze and start the target application. If the application is not frozen, it will be started directly. name="package" value="com.package.name"

com.aistra.hail.action.FREEZE: Freeze the target application. The application must be on the home page. name="package" value="com.package.name"

com.aistra.hail.action.UNFREEZE: Unfreeze the target application. name="package" value="com.package.name"

com.aistra.hail.action.FREEZE_TAG: Freeze all non-whitelisted applications in the target tag. name="tag" value="tag name"

com.aistra.hail.action.UNFREEZE_TAG: Unfreeze all applications in the target tag. name="tag" value="tag name"

com.aistra.hail.action.FREEZE_ALL: Freeze all applications on the home page. No extra required.

com.aistra.hail.action.UNFREEZE_ALL: Unfreeze all homepage apps. No extra required.

com.aistra.hail.action.FREEZE_NON_WHITELISTED: Freeze all non-whitelist apps on the homepage. No extra required.

com.aistra.hail.action.FREEZE_AUTO: Automatically freeze homepage apps. No extra required.

com.aistra.hail.action.LOCK: Lock the screen. No extra required.

com.aistra.hail.action.LOCK_FREEZE: Freeze all homepage apps and lock the screen. No extra required.

**Comment by palmuse** [comment]
Example in Tasker ADB Wifi:

am start -a com.aistra.hail.action.FREEZE_TAG -e tag Default
