### ISSUE TITLE
switch of fuzzy search

### ISSUE THREAD

**Issue by rahaaatul** [aistra0528/Hail#239]
It's showing irrelevant apps in the search:

https://github.com/aistra0528/Hail/assets/86149861/b044c8c9-5cde-4a6f-838d-58e6da422010

You can see what I'm searching doesn't match with other apps, but they're still being shown.

**Comment by Ten-Shine** [comment]
They use Levenshtein distance to implement fuzzy search. 
If the Levenshtein distance between the two strings is less than the length of the original string and the original string contains each character of the input string in sequence, it will be shown.

https://github.com/aistra0528/Hail/blob/master/app/src/main/kotlin/com/aistra/hail/utils/FuzzySearch.kt#L9
```
    /**
     * 两个字符串差异小于原始字符串长度 且 原始字符串依次包含输入字符串的每个字符 则显示在搜索结果中
     * @param raw 需要匹配的原始字符串
     * @param query 输入的字符串
     */
    fun search(raw: String?, query: String?): Boolean {
        if (query.isNullOrEmpty()) return true
        if (raw.isNullOrEmpty()) return false
        if (raw.contains(query, true)) return true
        val rawUpp = raw.uppercase()
        val queryUpp = query.uppercase()
        val diff = levenshteinDistance.apply(rawUpp, queryUpp)
        return diff < rawUpp.length && containsInOrder(rawUpp, queryUpp)
    }
```

I think it is better to make a preference of the fuzzy search for users to decide what they want.

**Comment by rahaaatul** [comment]
> They use Levenshtein distance to implement fuzzy search. If the Levenshtein distance between the two strings is less than the length of the original string and the original string contains each character of the input string in sequence, it will be shown.
> 
> https://github.com/aistra0528/Hail/blob/master/app/src/main/kotlin/com/aistra/hail/utils/FuzzySearch.kt#L9
> 
> ```
>     /**
>      * 两个字符串差异小于原始字符串长度 且 原始字符串依次包含输入字符串的每个字符 则显示在搜索结果中
>      * @param raw 需要匹配的原始字符串
>      * @param query 输入的字符串
>      */
>     fun search(raw: String?, query: String?): Boolean {
>         if (query.isNullOrEmpty()) return true
>         if (raw.isNullOrEmpty()) return false
>         if (raw.contains(query, true)) return true
>         val rawUpp = raw.uppercase()
>         val queryUpp = query.uppercase()
>         val diff = levenshteinDistance.apply(rawUpp, queryUpp)
>         return diff < rawUpp.length && containsInOrder(rawUpp, queryUpp)
>     }
> ```
> 
> I think it is better to make a preference of the fuzzy search for users to decide what they want.

The code is a bit over my head, but I'm on board. Let's skip the fuzzy search as a defualt, but maybe we can have a 'just-in-case' switch for the future if needed.

**Comment by Ten-Shine** [comment]
You can change your title to ask for a switch about fuzzy search.

**Comment by rahaaatul** [comment]
> You can change your title to ask for a switch about fuzzy search.

Don't you think **🐛 Search is not working correctly** will catch his attention better?
