### ISSUE TITLE
Hail does not freeze all apps when pressing freeze button, which is set to freeze all by default

### ISSUE THREAD

**Issue by Nemix777** [aistra0528/Hail#244]
I have a problems with Hail not not freezing all apps when pressing freeze button, which is set to freeze all by default.

It will only freeze apps in the current tag/tab and doe not freeze the rest of the unfrozen apps in other tags/tabs.
![Screenshot_2024-06-10-20-15-23-651_com aistra hail 1](https://github.com/aistra0528/Hail/assets/172336333/b1417ad0-7dd2-493e-b817-7944d91ca437)
![Screenshot_2024-06-10-20-15-25-961_com aistra hail 1](https://github.com/aistra0528/Hail/assets/172336333/55d03228-122d-4f11-8097-854996a01171)
![Screenshot_2024-06-10-20-15-43-319_com aistra hail 1](https://github.com/aistra0528/Hail/assets/172336333/1502d6a4-02b1-432e-8aa4-c15a5ee77580)
![Screenshot_2024-06-10-20-20-25-517_com aistra hail 1](https://github.com/aistra0528/Hail/assets/172336333/98731b9e-baea-4628-b2b2-e4f6f0212769)

**Comment by chaoscreater** [comment]
Pretty sure that's normal.

The button is a "button". It's not a "tile". The tile is referring to the Quick Tile that you see when you pull down the notification shade from the top of the screen. You can add a Hail tile in there and pressing that will do what the setting in your first screenshot is configured to do.

When you press the button, it will only freeze apps on the current tag page. If you want to freeze all, you need to long press it.

Alternatively, you can go to the Settings screen and go right to the bottom, set the dynamic shortcut action to Freeze all and add to home screen. The shortcut will do what you configure it to do.

Lastly, you can use apps like Tasker or MacroDroid to send shell commands to Hail to automate a lot of the freezing processes. You can freeze individual apps, or freeze all non-whitelisted apps, or freeze ALL apps, or freeze apps with a specific tag, etc. These commands are found on the project's home page, it's all there.
