### ISSUE TITLE
Not able to remove the app from admin device

### ISSUE THREAD

**Issue by vippium** [aistra0528/Hail#261]
I tried to remove the app from device admin but it is not working. I also tried with adb too but not. Can you share the adb command to remove it from admin device.

**Comment by brnslmn** [comment]
Had this issue. Not exactly clear, but there is a button on the top-right in Settings to remove it.

**Comment by vippium** [comment]
> Had this issue. Not exactly clear, but there is a button on the top-right in Settings to remove it.

Thanks...Closing the issue
