### ISSUE TITLE
优化暂停和冻结一起用的逻辑。

### ISSUE THREAD

**Issue by wochenjinghe** [aistra0528/Hail#268]
我用喜欢暂停大部分app，但是有些app暂停也会后台启动，
若冻结全部app会从桌面消失。

麻烦优化暂停和冻结一起用的逻辑。
在全部一起操作时，让个别app支持自定义设置的冻结，而不是听通过批量设置模式，或者你们提供一个脚本一样的东西，我自己编写。
如果可以请生成一个冻结后的启动快捷方式。

**Comment by vjaykrsna** [comment]
Yeah instead of a single working mode or say state of app, if we are able to choose different state per app basis it would be better like categorizing. Like we want to disable some junk all together and just suspend some frequently used apps to be visible in launcher greyed out.

**Comment by wochenjinghe** [comment]
> [#83](https://github.com/aistra0528/Hail/issues/83)

感谢回复，预祝你新春快乐！
