### ISSUE TITLE
Shizuhu 停用授权，冻结和打开桌面快捷方式发生没有权限

### ISSUE THREAD

**Issue by sherlcok314159** [aistra0528/Hail#277]
开发者你好，首先感谢你们开发了如此棒的工具，我个人是小黑屋付费用户，想着支持开源就来使用一下

当我使用 Shizuku 来授权后，我冻结软件时（非系统级别应用）以及打开桌面添加的快捷方式，*均有概率* 提醒我「没有权限」。但更奇怪的是，当提醒完没有权限后，其实桌面上已经解冻了该应用

以下信息供开发者排查：

```
OS: Android 12, 鸿蒙 3，P40
Hail:  1.9.0 (33)
Shizuku: 13.5.4
```

**Comment by ChenYFan** [comment]
#278

**Comment by sherlcok314159** [comment]
@aistra0528 方便 released 一版嘛？不然用 CLI 打包的签名不一致覆盖安装不了

**Comment by aistra0528** [comment]
> @aistra0528 方便 released 一版嘛？不然用 CLI 打包的签名不一致覆盖安装不了

[Hail-v1.9.0-1546bf9.zip](https://github.com/user-attachments/files/17968422/Hail-v1.9.0-1546bf9.zip)

**Comment by sherlcok314159** [comment]
@aistra0528 通过手机下拉栏的磁贴「全部冻结」一样发生没有权限的情况，实际上已经冻结好了，这个 bug 没修嘛
