### ISSUE TITLE
扩展 API ：增加设置冻结、解冻模式的参数

### ISSUE THREAD

**Issue by luowue** [aistra0528/Hail#284]
不同的冻结模式有不同的特征，比如，Shizuku(adb) 不能冻结一些系统应用，Dhizuku可以；Shizuku(adb) 冻结的应用不会丢失权限，但 Dhizuku 冻结会丢失权限；不同模式的冻结/解冻速度也有差别。如果可以在使用 API 时设置冻结／解冻模式，就可以根据 app 的使用需求灵活的对不同 app 使用不同的冻结／解冻模式，避免使用不同模式冻结／解冻 app 时手动到雹页面内切换模式，操作繁琐。
或者还有一个方法：让首页中每个分组可以独立设置冻结/解冻模式（就很强）。

**Comment by aistra0528** [comment]
#83
