### ISSUE TITLE
重新打开应用之后权限被重置

### ISSUE THREAD

**Issue by 2096779623** [aistra0528/Hail#30]
https://user-images.githubusercontent.com/57583560/180382203-6d5b7c2f-0e29-4b09-b173-14663cf15e26.mp4

安卓10
设备管理员模式
hail版本：0.9.6（17）
未root

https://t.me/hail_android/1177

貌似大部分应用的权限都这样，重启就要重新设置

**Comment by 2096779623** [comment]
> hide特性如此，嫌麻烦换模式或使用第三方appops类应用

为什么冰箱也是设备管理员，它能保留权限

**Comment by aistra0528** [comment]
冰箱 FAQ https://iceboxdoc.catchingnow.com/FAQ 常见问题

**Comment by lifei** [comment]
> hide特性如此，嫌麻烦换模式或使用第三方appops类应用

使用第三方appops类应用指的是什么？
