### ISSUE TITLE
一些界面的建议

### ISSUE THREAD

**Issue by arix00** [aistra0528/Hail#35]
1. 标签：
能否增加一个可选的“全部” 页和隐藏默认分类页的功能

2. 能否增加 彩色图标+自定义的不同颜色字体表示不同状态
现在的灰色图标 灰色字体看着有点累

3. 选择程序的时候，system和user应用分不同的页列出
而不是混到一起。
然后system包括显示在launcher里的各种预装软件和
更底层的隐藏app
二者危险度明显不同，再加一个选项控制是否显示隐藏的系统app
可以参考下空调狗airfrozen

谢谢。

**Comment by aistra0528** [comment]
会在1.0版本优化部分内容
