### ISSUE TITLE
一些建议 希望可以采纳

### ISSUE THREAD

**Issue by Franz611328** [aistra0528/Hail#36]
**1.关联启动**
希望可以添加从其他应用关联启动被冻结应用(不知道非root能不能实现此功能，大概率不行吧)。
**2.应用排序**
希望添应用加置低功能，当然要是能自由排序应用顺序最好。
**3.标签排序**
希望可以自由排序标签。虽然可以通过修改标签名来曲线救国，但标签多了后会比较麻烦。
**4.冻结全部应用**
希望可以添加一键冻结全部应用(在设置页面有看到此功能相关功能开关，但是貌似只能冻结当前标签页的全部应用而非冻结列表勾选的全部应用)。
**5.彩色图标**
希望在被冻结应用图标上或者应用名称上添加某种标识或者标签来实现区分已冻结应用。再者要是可以自定义应用图标包就最好了。
**6.滑动页面**
希望可以滑动标签页来进入相邻的标签页面。

**Comment by aistra0528** [comment]
会在1.0版本优化部分内容
