### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [aistra0528/Hail#5]
请问是否可以将应用发布到 F-Droid? 谢谢！

**Comment by aistra0528** [comment]
发，都可以发

**Comment by linsui** [comment]
我开了一个 [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10608)

**Comment by linsui** [comment]
已合并，感谢你的帮助和支持！应用会在两到三天内进入存储库。F-Droid 的徽标

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.aistra.hail)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.aistra.hail)
```
