### ISSUE TITLE
Option to open app in search mode

### ISSUE THREAD

**Issue by G0V1NDS** [aistra0528/Hail#61]
Thanks for such an awesome app. I have almost suspended all the external apps in my phone using shizuku.
To open any of those apps I need to open the hail app and search for it, which seems like an extra effort.

It would be really helpful if we can have an option to open the app in search mode by default or a widget/shortcut to search the app from homescreen itself.

A search activity would also help which can be accessed using gesture or with a key mapper.

**Comment by rahaaatul** [comment]
@aistra0528 [Sesame](https://play.google.com/store/apps/details?id=ninja.sesame.app.edge) creates shortcuts when you open disabled apps with hail, but disappears after a day or two. Can you make the shortcut persistent in sesame search or when you disable an app it becomes a shortcut for the app? You can search disabled apps with sesame search and open it.
