### ISSUE TITLE
关于导入导出功能的疑问

### ISSUE THREAD

**Issue by tuyafeng** [aistra0528/Hail#65]
开发者你好，Hail 很好用，感谢你的开发。

在使用过程中，我对主页面菜单中的「导入应用」和「导出到剪贴板」感到困惑，所以希望了解你对这两个功能的看法和设置该功能的目的。

「导入应用」似乎是将剪贴板或是系统已经冻结的应用添加到应用列表。
「导出到剪贴板」似乎是将当前应用列表导出到剪贴板。

请问你设置这两个选项是为了做应用列表的备份吗？我觉得如果是为了备份的话，可以直接在设置中加入备份数据/导出数据的选项，将选中的应用列表导出到一个文件，再对该文件做解析就好了。如果是有其它的考虑，请告诉我。

如果你依旧更偏好通过剪贴板做备份的话，我认为可以将这两个菜单选项，移动到应用页面的菜单中，用户可以一键选中当前已冻结的应用（或一键选中剪贴板的应用），或是将已选中的应用拷贝到剪贴板。

因为我不明确该功能的具体目的，所以还没有改动这块的代码，希望你可以明确告诉我你的想法，这样我可以帮你完善这个功能。

**Comment by aistra0528** [comment]
“导入应用”和“导出到剪切板”功能主要并不是用于应用数据备份，而是方便用户初次使用时快速上手。

剪切板导入导出使用户之间可以快速分享冻结应用列表而不依赖截图或特定服务器，“导入已冻结应用”方便已使用 adb 或软件冻结过应用的用户进行快速设置。

目前雹还没有真正意义上的备份功能，如果你愿意的话欢迎贡献。

**Comment by aistra0528** [comment]
#93
