### ISSUE TITLE
操作习惯更改建议（现在的操作太反人类了）和卸载功能建议

### ISSUE THREAD

**Issue by bai12123** [aistra0528/Hail#66]
1.首页-app单击启动，长按弹出菜单。应用页-app单击弹出菜单，长按复制。2个页面的手势操作经常性搞混，反人类，建议统一手势操作
更改建议：应用页-app单击选中，长按弹出菜单

2.应用页-app弹出菜单-“应用信息”功能可否也添加在首页-app弹出菜单里。每次我想要使用应用信息这个功能的时候，都要在应用页进行搜索，然后选中app-应用信息 查看。太麻烦了

3.工作模式能否添加卸载功能，类似adb卸载

**Comment by aistra0528** [comment]
感谢建议，后续优化
