### ISSUE TITLE
permission denied even though I have shizuku

### ISSUE THREAD

**Issue by manavkulshrestha** [aistra0528/Hail#69]
Hi, how do I get hail to prompt shizuku instead of just saying permission denied? All other apps I have that use shizuku just did it automatically.

**Comment by UMLAUTaxl** [comment]
Seconded
Device: Samsung Galaxy A3 (2017)
Android 8.0.0

**Comment by UMLAUTaxl** [comment]
It seems it's a known issue. See #59
Comment 2 says "It is normal to set the administrator suspend mode, but shizuku's suspend mode has been unusable, and re-authorizing shizuku and uninstalling and reinstalling have no effect"
