### ISSUE TITLE
Feature Request: unfreeze two or multiple apps together with one shortcut 

### ISSUE THREAD

**Issue by rahaaatul** [aistra0528/Hail#73]
For apps like Revanced YouTube, you need microG (for non-root users). If both are disabled and you open YouTube it would not work, because microG must be present. So, for apps like these, can you add a feature to unfreeze multiple app with one shortcut?

Thank you Aistra, for this amazing app.

**Comment by Enkidu70** [comment]
Good idea. I'd need the same...

**Comment by rahaaatul** [comment]
@aistra0528 Can you do a chain unfreeze with this? For example, you create a shortcut for a tag called YouTube, which contains YouTube Revanced and Vanced microG. 
When you tap the YouTube shortcut in home screen, first it'll open microG then YouTube. Is this possible?

**Comment by rahaaatul** [comment]
@aistra0528 please consider adding this feature...

Enable and open pinned item and also enable other items in the tag.

**Comment by rahaaatul** [comment]
Thank you @aistra0528 , you're a G!
