### ISSUE TITLE
Feature Request: Ability to sort apps in Home

### ISSUE THREAD

**Issue by takomine** [aistra0528/Hail#79]
I'm hoping that, like in the Apps tab, we can sort the apps by whether they're user apps or system apps. It becomes a mess when you have many selected apps and you can't arrange them. Maybe the ability to make a custom group of apps to display in Home would also be nice.

**Comment by aistra0528** [comment]
You can set tags for the apps in Home.

**Comment by takomine** [comment]
Oh, I didn't know it would be categorized like that. I wish it were easier to do instead of selecting each tag individually.

Like when you select a category, there will be a button (like a plus sign) that you can click where it will display all apps by default, and then you can choose from there what to include in your tag. Anyway, it's all good.

**Comment by chaoscreater** [comment]
> Oh, I didn't know it would be categorized like that. I wish it were easier to do instead of selecting each tag individually.
> 
> Like when you select a category, there will be a button (like a plus sign) that you can click where it will display all apps by default, and then you can choose from there what to include in your tag. Anyway, it's all good.

I just started using Hail today and came across this. For anyone else who may be wondering the same question, you can multi-select multiple apps in Home and then long press one of the selected apps to set tags. When you long press, the action you apply will apply to all selected apps.
