### ISSUE TITLE
Can't remove device owner

### ISSUE THREAD

**Issue by A7pr8** [aistra0528/Hail#82]
The only way I found on the net was to use:
`dpm remove-active-admin`

But it demands the app to have android:testonly

Another way was to have inside the app an activity to disable device owner which hail doesn't have and its not in the settings of the app

I can't uninstall the app because it always fail even while using `pm uninstall com.aistra.hail`

The only way to remove the app now from device owner is by factory reset 

I am not a devloper and I actually don't really understand any of these but that what I was able to understand from the net

I really love this app and I hope there will be a fix for this

Sorry for my bad English

**Comment by aistra0528** [comment]
Is Hail still active device admin now?
![IMG_20230204_203305](https://user-images.githubusercontent.com/55940744/216767864-03573499-ffa7-4318-9b9e-776fd4799014.jpg)

**Comment by A7pr8** [comment]
Found the solution:
Open hail --> apps --> enable hail there then hold it and uninstall

You really need to do that specifically 

Anyway thanks for replying
