### ISSUE TITLE
切换冻结模式bug

### ISSUE THREAD

**Issue by demolg** [aistra0528/Hail#84]
使用shizuku-停用方式冻结应用后，切换到shizuku-暂停模式，已经被“停用”的应用没有被转换为“暂停”的应用，导致这些应用无法解冻，需要切换回shizuku-停用模式才可以解冻

**Comment by qanyan** [comment]
这不是正常的逻辑吗，什么方式冻结就用什么方式解冻

**Comment by demolg** [comment]
@qanyan 逻辑上是这样，但应用操作上就很繁琐，而且被冻结的应用也没有被冻结方式的标记，我可记不住这么多应用分别是怎么被冻结的
