### ISSUE TITLE
[Feature Request] Sort and Swipe

### ISSUE THREAD

**Issue by ideal4ever** [aistra0528/Hail#94]
Hi there,

Just wanted to express my appreciation and also ask for a few tweaks to the app if possible :
- sort options for tags
- switching between tags/tabs by swiping left/right

thanks,
Moh

**Comment by rahaaatul** [comment]
Hey @aistra0528 ❤️

Please add the feature to **rearrange tags by long tapping and rearranging them.** This will help prioritize later created tags that are more important, preventing them from getting hidden among other tabs and requiring extra swiping to locate them.

**Comment by Nriver** [comment]
Rearrange tag is quite useful when you made lots of tags for hundreds of apps. I want this feature too.

**Comment by aistra0528** [comment]
#242
